[package]
edition = "2024"
name = "webhook_emitter"
publish = false
version = "0.1.0"

[features]
bridge = [
  "dep:channels",
  "dep:document_sub_type",
  "dep:documents",
  "dep:kafka_util",
  "dep:macro_event_broker",
  "dep:macro_event_topics",
  "dep:rdkafka",
  "dep:tokio-retry",
]
default = ["bridge", "worker"]
worker = ["dep:reqwest", "dep:tokio", "dep:tokio-util"]

[dependencies]
anyhow = { workspace = true }
channels = { path = "../channels", default-features = false, optional = true }
chrono = { workspace = true }
document_sub_type = { path = "../document_sub_type", optional = true }
documents = { path = "../documents", default-features = false, optional = true }
hex = { workspace = true }
hmac = { workspace = true }
kafka_util = { path = "../kafka_util", optional = true }
macro_event_broker = { path = "../macro_event_broker", default-features = false, features = [
  "outbound",
], optional = true }
macro_event_topics = { path = "../macro_event_topics", optional = true }
rdkafka = { workspace = true, optional = true }
reqwest = { workspace = true, optional = true }
serde = { workspace = true }
serde_json = { workspace = true }
sha2 = { workspace = true }
sqlx = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true, features = ["macros", "time"], optional = true }
tokio-retry = { workspace = true, optional = true }
tokio-util = { workspace = true, optional = true }
tracing = { workspace = true }
uuid = { workspace = true }
workspace-hack = { version = "0.1", path = "../workspace-hack" }

[dev-dependencies]
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }
wiremock = { workspace = true }
