[package]
edition = "2024"
name = "sync_machine_2"
publish = false
version = "0.1.0"

[dependencies]
sync_machine = { path = "../sync_machine" }
thiserror = { workspace = true }
tokio = { workspace = true, features = ["macros", "rt", "sync", "time"] }
tracing = { workspace = true }
workspace-hack = { version = "0.1", path = "../workspace-hack" }

[dev-dependencies]
tokio = { workspace = true, features = ["macros", "rt", "sync", "time", "test-util"] }
